# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

 source 'https://github.com/CocoaPods/Specs.git'
target 'Enqura' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
 
  # Pods for EnverifyIOSDemo
  pod 'Toaster'
  pod 'IQKeyboardManagerSwift'
  pod 'SnapKit', '~> 5.0.0'

  # Pods for EnVerify
#  pod 'Starscream', '~> 3.0.0'
#  pod 'GoogleWebRTC'
#  pod 'Socket.IO-Client-Swift'
#  pod 'Alamofire', '~> 5.5.0'
#  pod 'GoogleMLKit/TextRecognition','2.2.0'
#  pod 'GoogleMLKit/FaceDetection'
#  pod 'GoogleMLKit/BarcodeScanning'
# 
#  pod 'OpenSSL-Universal','1.1.1900'
#  pod 'SwiftyJSON', '~> 5.0'
#  pod 'TensorFlowLiteSwift'
  pod 'EnVerify','1.3.13.6'
  pod 'netfox', :configurations => ['Debug']
 
end

post_install do |installer|
        installer.pods_project.targets.each do |target|
          target.build_configurations.each do |config|
            config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
            config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
            config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
            config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
          end
        end
      end


